front_folder: dataset/3D-FRONT
future_folder: dataset/3D-FUTURE-model
anime_folder: dataset/DeformingThings4D/humanoids
anime_folder_animals: dataset/DeformingThings4D/animals
shapenet_folder: dataset/ShapeNetCore.v2

shapenet_json: code/BlenderProc/examples/datasets/front_3d/config/shape.json
dt4_json: code/BlenderProc/examples/datasets/front_3d/config/dt4.json

output_dir: dataset/3D-Deforming-FRONT-v5

flow_skip: 4
anime_per_scene: 36
random_animals: 96

camera_to_furniture: 1.5
sample_camera_loc: 12

render_width: 640
render_height: 480
render_samples: 128

anim_distance_to_camera: 1.8
multi_anime: 1

#furniture_sample_surface
sample_shapenet_num: 5
sample_on_normal_furniture: 25
sample_on_cabinet: 20
min_sample: 10
sample_obj_size: 0.35

#sample_obj_nearby
random_shapenet: 30
random_shapenet_size: 0.35
random_shapenet_radius: 3.0
random_shapenet_dis_to_cam: 1.3
random_shapenet_min_h: 0.1
random_shapenet_max_h: 2.5

#multi_anim
multi_anim_dis_to_center: 1.2
multi_anim_min_dis: 0.5
multi_anim_dis_to_cam: 2.4

#render_anim
render_offset_thrs: 0.25
render_cam_random_loc_off: 0.35
render_proportion_min: 0.1
render_proportion_mid: 0.3
render_proportion_max: 0.5

render_anim_moving_dis_max: 0.2
render_anim_moving_dis_min: 0.1
render_anim_moving_dis_to_cam: 1.1
render_anim_moving_rot: 15
render_anim_moving_max_h: 1.6

render_shapenet_moving_dis: 0.1
render_shapenet_moving_dis_to_cam: 1.3

render_furniture_nearby_thrs: 4.5
render_furniture_nearby_loc_off: 0.2
render_furniture_nearby_to_cam: 1.3

render_d2p_min_clip: 0.3
render_d2p_max_clip: 5.5
render_d2p_voxel_size: 0.025
render_d2p_flat_area: 2.4

render_min_points: 3000
render_overlap_min: 0.1
